### ISSUE TITLE
MacOS M1 Support

### ISSUE THREAD

**Issue by 3x3cut0r** [mPyKen/ScreenAreaShare#10]
Hi
on the releases page there is no asset for M1 macs. Maybe you can add my compiled version:
[ScreenAreaShare-1.3.2-arm64.dmg](https://drive.google.com/file/d/10DSVo-_UZ4_Jpn3p197cQBmCBhcpE-7V/view?usp=sharing)

Thank you

**Comment by mPyKen** [comment]
thanks! let me create a link to this issue

**Comment by di11ard** [comment]
hmmm... I downloaded from the link and tried running on my M1 Mac, but I am getting an error stating the file is damaged. 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/36542938/216721773-18dba12b-52d7-4842-80bf-352ce4459be7.png">

**Comment by di11ard** [comment]
@3x3cut0r 

hmmm... I downloaded from the link and tried running on my M1 Mac, but I am getting an error stating the file is damaged. 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/36542938/216721773-18dba12b-52d7-4842-80bf-352ce4459be7.png">

**Comment by 3x3cut0r** [comment]
hi, i do not use this app anymore. but maybe you can build a working version by yourself using nodejs 14?
maybe i clould do it but time is short for my atm. and i dont know if somethin would change.
