### ISSUE TITLE
Cpu Usage , no framerate limiter

### ISSUE THREAD

**Issue by 25pinjo15** [mPyKen/ScreenAreaShare#15]
Really a nice tool to use ! , But an parameter to add like max fps 60, 30 , 15 would be nice , while sharing code it would prevent fan to ramp up , just need 15 fps when sharing visual studio .

**Comment by mPyKen** [comment]
thanks! right, that would be a nice addition. do you know if electron provides a simple parameter to limit frame rate by any chance? i will see if i can find the time to look into this:)

**Comment by 25pinjo15** [comment]
sadly no  :(

**Comment by 25pinjo15** [comment]
But I did clone the repo and tried some stuff , still no luck but you will know if I found something

**Comment by 25pinjo15** [comment]
just tried that : 
`video: {
      mandatory: {
        chromeMediaSource: "desktop",
        chromeMediaSourceId: source.id,
        minWidth: display.bounds.width,
        minHeight: display.bounds.height,
        maxFrameRate: 5
      },
      
    },`

and it work ! . I did try  before maxfps , fps , ect ect XD

**Comment by 25pinjo15** [comment]
I made a build with a 15 fps limit . really slow down the fan on my laptop . An i7 in a 13 inch does make some heat XD

**Comment by mPyKen** [comment]
awesome! i will add a command line option in the next release:)
