### ISSUE TITLE
The shared area is darker than the real screen.

### ISSUE THREAD

**Issue by GendronAC** [mPyKen/ScreenAreaShare#2]
This is an odd one, hope you'll be able to help. I noticed that the "Main Window" screen was darker than the original one. 

How I view it with my eyes :
![IMG_20211231_105900433](https://user-images.githubusercontent.com/45271725/147831550-bfd3211a-2a2b-438a-9fdd-9ad79b523a9e.jpg)

Surprisingly when I do a screenshot both rectangles are similar (and darker): 
![image](https://user-images.githubusercontent.com/45271725/147831439-7ab7a09c-996d-4bcb-9183-b6bf8f5694e6.png)

Do you have any idea on what can cause this and how to fix it ?

**Comment by mPyKen** [comment]
Hmm... To find out if it is a user setting, could you try logging into your system with another account and see if the problem persists?

**Comment by GendronAC** [comment]
Tried with another user on the same laptop, same issue.

**Comment by mPyKen** [comment]
This is very odd... Sorry, I have no idea. My only guess would be any pre-installed bloatware or some other software installed afterwards.

**Comment by GendronAC** [comment]
Alright then, close the issue. And if I ever find out what or why I'll
reopen it and let you know.

AC
