### ISSUE TITLE
manually minimize render window

### ISSUE THREAD

**Issue by nnako** [mPyKen/ScreenAreaShare#20]
When starting `ScreenAreaShare`, both windows (for capture and for render) open at their user-desired locations on any screen, respective to their starting coordinates and size. Both screens will always be fully visible (as long as they are not bigger than the hosting screen). Both windows open on top of all other windows (which is standard for new applications on Windows OS).

Now, the capure window is identified by a thick red border, so I don't need to see the render window in order to know e.g. what is being shown to other people looking at my shared screen. And for me, hosting the render window in my monitors reduces the available window space to work on things while presenting to the folks.

Why not minimizing the render window in those cases? Although I love the borderless rendering, I would like to be able to see a small icon (as standard at least on Windows application windows) on the top right of the render window to be able to minimize the render window. While it's content is still being transferred to people on the other side of the share.

**Would it be possible to operate a small "minimize" icon to be able to put the render window out of local sight?**

If this is a bad idea, please tell me. Otherwise I might be able to implement this, myself.

**Comment by mPyKen** [comment]
If you minimize the render window, recording of it stops, so it cannot be minimized. You can, however, put other windows on top of the render window during recording

**Comment by nnako** [comment]
Understand. It makes sense to be able to not have to keep it in front when transferring its content. That will be fine for me, then.
