### ISSUE TITLE
command line options does not work

### ISSUE THREAD

**Issue by paddock3d** [mPyKen/ScreenAreaShare#9]
.\screen-area-share-1.3.2.Setup.exe --cw=1920 --ch=1080 --cx=0 --cy=0 --rx=3100 --ry=0 --freeze

For example , none of this commands are working.

**Comment by mPyKen** [comment]
The `*.Setup.exe` file actually installs the app for the current user and launches it automatically. The actual executable can be found under `%HOMEPATH%\AppData\Local\screen-area-share\screen-area-share.exe` which should support command line parameters.

**Comment by paddock3d** [comment]
thanks
